name: Wildernether

author: SchnTgaiSpock

description: 黏液科技附加「荒野地獄」繁體中文版。

main: me.schntgaispock.wildernether.Wildernether

website: https://github.com/SchnTgaiSpock/Wildernether

version: ${project.version}

api-version: 1.14

depend:
  - Slimefun

softdepend:
  - SlimeHUD
  - Gastronomicon

loadbefore:
  - SlimeCustomizer